quiz/urls.py
from django.urls import path

from . import views


app_name = "quiz"
urlpatterns = [
    # ex: /quiz/
    path("", views.index, name="index"),
    # all quiz
    path("allquiz/", views.allquiz, name="allquiz"),


    # ex: /quiz/5/
    path("<int:quiz_id>/<str:token>/", views.single_quiz, name="single_quiz"),
    # ex: /quiz/5/3/
    path(
        "q/<int:quiz_id>/<int:question_id>/<str:name>/",
        views.single_question,
        name="single_question",
    ),
    # ex: /quiz/5/3/vote/
    path("<int:quiz_id>/<int:question_id>/<str:name>/vote/", views.vote, name="vote"),
    # ex: /quiz/5/results/
    path("r/<int:quiz_id>/<str:name>/results/", views.results, name="results"),
    # ex: /quiz/create/
    path("create/", views.create_quiz, name="create_quiz"),
    # ex: /quiz/create/7/2/
    path(
        "create/<int:quiz_id>/<int:question_id>/",
        views.create_question,
        name="create_question",
    ),
    path("exam/", views.code_to_exam, name="exam"),
    path("create_exam/", views.create_exam, name="create_exam"),
    path("register_exam/", views.register_exam, name="register_exam"),
    path("update/<int:quiz_id>/<int:question_id>/<str:token>/", views.candidate_update, name="candidate_update"),
    path("report/", views.report, name="report"),

]

quiz_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("quiz.urls")),
]
# urlpatterns += staticfiles_urlpatterns()

quiz/models.py
from django.db import models


# Create your models here.
class Quiz(models.Model):
    quiz_title = models.CharField(max_length=300)
    num_questions = models.IntegerField(default=0)

    def __str__(self):
        return self.quiz_title


class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    question_text = models.CharField(max_length=300)
    question_num = models.IntegerField(default=0)

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=300)
    correct = models.BooleanField(default=False)

    def __str__(self):
        return self.choice_text
    

class Code(models.Model):
    name = models.CharField(max_length=300)
    email =  models.CharField(max_length=300)
    token= models.CharField(max_length=8)
    isexpired=models.BooleanField(default=False)
    quizid=models.IntegerField(default=0)

    def __str__(self):
        return self.token

class Candidate(models.Model):
    email = models.CharField(max_length=300)
    quiz_name = models.CharField(max_length=300)
    token = models.CharField(max_length=8)
    name = models.CharField(max_length=300)
    total_qn = models.IntegerField(default=0)
    correct_qn = models.IntegerField(default=0)
    wrong_qn = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.email

quiz/forms.py
from django import forms

from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _


# form to create a new quiz
class CreateQuizForm(forms.Form):
    quiz_name = forms.CharField(
        max_length=50,
        label="Quiz Name",
        widget=forms.TextInput(attrs={"class": "quiz_name_box"}),
    )
    num_questions = forms.IntegerField(
        label="Number of Questions",
        widget=forms.NumberInput(attrs={"class": "num_questions_box"}),
    )

    def clean_name(self):
        data = self.cleaned_data["quiz_name"]

        # Check if quiz name is unique.
        if data == "Default_Name":
            raise ValidationError(_("Invalid name - Must be Unique"))

        # returns cleaned data
        return data

    def clean_num_questions(self):
        data = self.cleaned_data["num_questions"]

        # Check if number of questions is at least 1 and is an integer
        if (isinstance(data, int) == False) or (data < 1):
            raise ValidationError(_("Invalid number - must be positive integer"))

        # Remember to always return the cleaned data.
        return data


# form to create questions with choices for each quiz
class CreateQuestionForm(forms.Form):
    question_text = forms.CharField(
        max_length=300,
        label="Question Text",
        widget=forms.TextInput(attrs={"class": "question_text_box"}),
    )

    choice1_text = forms.CharField(
        max_length=300,
        label="Choice 1",
        widget=forms.TextInput(attrs={"class": "choice_box"}),
    )
    choice1_correctness = forms.BooleanField(
        label="Choice 1 Correct?",
        required=False,
        widget=forms.CheckboxInput(attrs={"class": "choice_correct_box"}),
    )

    choice2_text = forms.CharField(
        max_length=300,
        label="Choice 2",
        widget=forms.TextInput(attrs={"class": "choice_box"}),
    )
    choice2_correctness = forms.BooleanField(
        label="Choice 2 Correct?",
        required=False,
        widget=forms.CheckboxInput(attrs={"class": "choice_correct_box"}),
    )

    choice3_text = forms.CharField(
        max_length=300,
        label="Choice 3",
        widget=forms.TextInput(attrs={"class": "choice_box"}),
    )
    choice3_correctness = forms.BooleanField(
        label="Choice 3 Correct?",
        required=False,
        widget=forms.CheckboxInput(attrs={"class": "choice_correct_box"}),
    )

    choice4_text = forms.CharField(
        max_length=300,
        label="Choice 4",
        widget=forms.TextInput(attrs={"class": "choice_box"}),
    )
    choice4_correctness = forms.BooleanField(
        label="Choice 4 Correct?",
        required=False,
        widget=forms.CheckboxInput(attrs={"class": "choice_correct_box"}),
    )

    # makes sure that exactly one answer is selected to be true
    def clean(self):
        choice1_answer = self.cleaned_data["choice1_correctness"]
        choice2_answer = self.cleaned_data["choice2_correctness"]
        choice3_answer = self.cleaned_data["choice3_correctness"]
        choice4_answer = self.cleaned_data["choice4_correctness"]

        answer_list = [choice1_answer, choice2_answer, choice3_answer, choice4_answer]

        print(answer_list)

        trueCount = 0
        for answer in answer_list:
            if answer == True:
                trueCount += 1

        if trueCount != 1:
            raise ValidationError(_("Must have exactly one correct answer"))

        return self.cleaned_data

quiz/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

from .models import Quiz, Question, Choice,Code,Candidate

from .forms import CreateQuizForm, CreateQuestionForm
import uuid
import mymail
# Create your views here.


# index page of all quizzes
def index(request):
    all_quiz_list = Quiz.objects.all()
    context = {
        "all_quiz_list": all_quiz_list,
    }

    return render(request, "quiz/index.html", context)


# specific quiz splash screen
def single_quiz(request, quiz_id,token):
    quiz = get_object_or_404(Quiz, pk=quiz_id)
    num_questions = len(quiz.question_set.all())


    # Code.objects.filter(token=token).exists()
    if(token=="admin"):
        if num_questions == 0:
            quiz.delete()
            all_quiz_list = Quiz.objects.all()
            context = {
                "all_quiz_list": all_quiz_list,
            }
            return render(request, "quiz/index.html", context)

        quiz.num_questions = num_questions
        quiz.save()

        # resets accuracy info to 0
        request.session["num_correct"] = 0
        request.session["num_wrong"] = 0

        context = {
            "quiz": quiz,
            "num_questions": num_questions,
            "token":token,
              "quizid":quiz_id,
        }

        return render(request, "quiz/single_quiz.html", context)
    if(Code.objects.filter(token=token).exists()):
        cc=Code.objects.get(token=token)
        quizid=cc.quizid
        # deletes quiz and returns to home if no questions created
        if num_questions == 0:
            quiz.delete()
            all_quiz_list = Quiz.objects.all()
            context = {
                "all_quiz_list": all_quiz_list,
            }
            return render(request, "quiz/index.html", context)

        quiz.num_questions = num_questions
        quiz.save()

        # resets accuracy info to 0
        request.session["num_correct"] = 0
        request.session["num_wrong"] = 0

        context = {
            "quiz": quiz,
            "num_questions": num_questions,
            "token":token,
            "quizid":quiz_id,
        }

        return render(request, "quiz/single_quiz.html", context)
    
    else:
        return render(request, "quiz/expired.html")


# specific question view
def single_question(request, quiz_id, question_id,name):
    quiz = get_object_or_404(Quiz, pk=quiz_id)
    current_question = quiz.question_set.get(question_num=question_id)
    gem=""
    # get correct answer and sent it with response 
    try:
        gem = current_question.choice_set.get(correct=True)
    except:
        pass
    # Checks if currently on last question of quiz
    next_or_submit = "Next"
    last_question_check = False
    if question_id == (len(quiz.question_set.all())):
        last_question_check = True
        next_or_submit = "Submit"

    next_question_id = question_id + 1

    all_choices = current_question.choice_set.all()

    context = {
        "current_question": current_question,
        "all_choices": all_choices,
        "quiz": quiz,
        "next_question_id": next_question_id,
        "last_question_check": last_question_check,
        "next_or_submit": next_or_submit,
        "gem":gem,
        "name":name,
    }

    return render(request, "quiz/single_question.html", context)


# view that receives info from user's answer to question and determines correctness
def vote(request, quiz_id, question_id,name):
    quiz = get_object_or_404(Quiz, pk=quiz_id)
    current_question = quiz.question_set.get(question_num=question_id)
    
    # checks if current question is last one
    next_or_submit = "Next"
    if question_id == (len(quiz.question_set.all())):
        next_or_submit = "Submit"

    try:
        selected_choice = current_question.choice_set.get(pk=request.POST["choice"])
        print("------------------------------------------------------------------------------------")
        print(request.POST["choice"])
        print("------------------------------------------------------------------------------------")

    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form
        return render(
            request,
            "quiz/single_question.html",
            {
                "quiz": quiz,
                "current_question": current_question,
                "error_message": "You didn't select a choice.",
                "next_or_submit": next_or_submit,
                "name":name
            },
        )
    else:
        # get which choice is the correct answer
        correct_answer = current_question.choice_set.get(correct=True)

        if selected_choice == correct_answer:
            print("You are right")
            request.session["num_correct"] += 1
        else:
            print("You are wrong")
            request.session["num_wrong"] += 1

        # checks if next page should be results or next question
        if question_id == (len(quiz.question_set.all())):

            return HttpResponseRedirect(reverse("quiz:results", args=(quiz.id,name)))
        else:
           
            return HttpResponseRedirect(
                reverse(
                    "quiz:single_question",
                    args=(
                        quiz.id,
                        question_id + 1,
                        name
    
                    ),
                )
            )


# quiz results page
def results(request, quiz_id,name):
    quiz = get_object_or_404(Quiz, pk=quiz_id)

    num_correct = request.session["num_correct"]
    num_wrong = request.session["num_wrong"]

    total_questions = num_correct + num_wrong

    # formats accuracy as % with no decimal digits
    accuracy = num_correct / (total_questions)

    accuracy_over_75 = False
    if accuracy >= 0.75:
        accuracy_over_75 = True

    accuracy_formatted = "{:.0%}".format(accuracy)

    context = {
        "num_correct": num_correct,
        "num_wrong": num_wrong,
        "accuracy_over_75": accuracy_over_75,
        "accuracy_formatted": accuracy_formatted,
        "total_questions": total_questions,
        "quiz": quiz,
    }
    obj=Candidate.objects.get(name=name)
    obj.total_qn=total_questions
    obj.correct_qn=num_correct
    obj.wrong_qn=num_wrong
    obj.save()
    return render(request, "quiz/results.html", context)


# view for create quiz page
def create_quiz(request):
    # If this is a POST request then process the Form data
    if request.method == "POST":
        # Create a form instance and populate it with data from the request (binding):
        form = CreateQuizForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            quiz_name = form.cleaned_data["quiz_name"]
            num_questions = form.cleaned_data["num_questions"]

            new_quiz = Quiz(quiz_title=quiz_name, num_questions=num_questions)
            new_quiz.save()

            # redirect to a new URL:
            return HttpResponseRedirect(
                reverse(
                    "quiz:create_question",
                    args=(
                        new_quiz.id,
                        1,
                    ),
                )
            )

    # If this is a GET (or any other method) create the default form.
    else:
        form = CreateQuizForm()

    context = {
        "form": form,
    }

    return render(request, "quiz/create_quiz.html", context)


# view for create quiz page
def create_question(request, quiz_id, question_id):
    # gets current quiz
    quiz = Quiz.objects.get(pk=quiz_id)

    # If this is a POST request then process the Form data
    if request.method == "POST":
        # Create a form instance and populate it with data from the request (binding):
        form = CreateQuestionForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            question_text = form.cleaned_data["question_text"]

            choice1 = form.cleaned_data["choice1_text"]
            choice1_correctness = form.cleaned_data["choice1_correctness"]

            choice2 = form.cleaned_data["choice2_text"]
            choice2_correctness = form.cleaned_data["choice2_correctness"]

            choice3 = form.cleaned_data["choice3_text"]
            choice3_correctness = form.cleaned_data["choice3_correctness"]

            choice4 = form.cleaned_data["choice4_text"]
            choice4_correctness = form.cleaned_data["choice4_correctness"]

            # creates question in quiz
            question = Question(
                quiz=quiz, question_text=question_text, question_num=question_id
            )
            question.save()

            # creates choices for questions
            question.choice_set.create(choice_text=choice1, correct=choice1_correctness)
            question.choice_set.create(choice_text=choice2, correct=choice2_correctness)
            question.choice_set.create(choice_text=choice3, correct=choice3_correctness)
            question.choice_set.create(choice_text=choice4, correct=choice4_correctness)

            # redirect to home if done or next create question page if not
            if question_id == quiz.num_questions:
                return HttpResponseRedirect(reverse("quiz:index"))
            else:
                return HttpResponseRedirect(
                    reverse(
                        "quiz:create_question",
                        args=(
                            quiz_id,
                            question_id + 1,
                        ),
                    )
                )

    # If this is a GET (or any other method) create the default form.
    else:
        form = CreateQuestionForm()

    if question_id == quiz.num_questions:
        next_submit = "Submit"
    else:

quiz/templates/quiz/allquiz.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'quiz/allquiz.css' %}">

    <meta charset="UTF-8">
    <title>Index</title>

</head>

<body>
   
    {% include 'quiz/navbar.html' %}

        
    </section>
    <div class="createbutton">
        <a href="{% url 'quiz:create_quiz' %}">CREATE QUIZ</a>
        <a href="{% url 'quiz:create_exam' %}">CREATE EXAM</a>
    </div>
    <div class="result_container" >
        <table id="results">
            <tr>
                <td>
                    Name
                </td>
                <td>
                    questions
                </td>
                <td>
                    
                </td>
            </tr>
            {% if all_quiz_list %}
                {% for quiz in all_quiz_list %}
                <tr>
                    <td>
                        {{ quiz.quiz_title }}
                    </td>
                    <td>{{ quiz.num_questions }}</td>
                    <td>
                        <a class="card" href="{% url 'quiz:single_quiz' quiz.id 'admin' %}">open</a>
                    </td>
                </tr>
               
    
                {% endfor %}
        {% else %}
            <p>No quizzes are available.</p>
        {% endif %}
        </table>
    </div>
    
   
</body>

</html>

quiz/templates/quiz/create_exam.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Skill Ninja</title>
    <link rel="stylesheet" type="text/css" href="{% static 'quiz/create_exam.css' %}">

</head>
<body>
    {% include 'quiz/navbar.html' %}

   <div class="container">

    <form id="create_exam" autocomplete="on" action="{% url 'quiz:register_exam'%}" method="post">
        {% csrf_token %}

        <label for="fname">Enter Name:</label>
        <input type="text" id="name" name="name">

        <label for="fmail">Enter Mail:</label>
         <input type="text" id="mailid" name="mailid">

        <label for="cars">Choose a Quiz:</label>
        <select id="quiz" name="quizid">

            {% if all_quiz_list %}
                {% for quiz in all_quiz_list %}
           
            <option value="{{quiz.id}}">{{ quiz.quiz_title }}</option>
                {% endfor %}
            {% else %}
                <p>No quizzes are available.</p>
            {% endif %}

        </select>
        <button  type="submit" form="create_exam" value="Submit">create exam</button>
      </form>
   </div>
</body>
</html>

quiz/templates/quiz/create_question.html
<!DOCTYPE html>
<html lang="en">

<head>

    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'quiz/create_question.css' %}">

    <meta charset="UTF-8">
    <title>Create Question</title>

</head>

<body>

    {% include 'quiz/navbar.html' %}



    <div class="form_wrapper">

        <h1 class="form_name">Create Question {{ question_num }}</h1>

        <form action="" method="post">
            {% csrf_token %}
            <div class="error_text">
                {{ form.non_field_errors }}
            </div>

            <div class="question_text_wrapper">
                {{ form.question_text.errors }}
                <label class="question_text_label" for="{{ form.question_text.id_for_label }}">Question Text: </label>
                {{ form.question_text }}
            </div>

            <div class="choice1">

                <div class="choice_text_wrapper">
                    {{ form.choice1_text.errors }}
                    <label class="choice_label" for="{{ form.choice1_text.id_for_label }}">Choice 1: </label>
                    {{ form.choice1_text }}
                </div>

                <div class="choice_correct_wrapper">
                    {{ form.choice1_correctness.errors }}
                    <label class="choice1_correct_label" for="{{ form.choice1_text.id_for_label }}"></label>
                    {{ form.choice1_correctness }}

                </div>

            </div>

            <div class="clear"></div>

            <div class="choice2">

                <div class="choice_text_wrapper">
                    {{ form.choice2_text.errors }}
                    <label class="choice_label" for="{{ form.choice2_text.id_for_label }}">Choice 2: </label>
                    {{ form.choice2_text }}
                </div>

                <div class="choice_correct_wrapper">
                    {{ form.choice2_correctness.errors }}
                    <label class="choice2_correct_label" for="{{ form.choice2_text.id_for_label }}"></label>
                    {{ form.choice2_correctness }}
                </div>

            </div>

            <div class="clear"></div>

            <div class="choice3">

                <div class="choice_text_wrapper">
                    {{ form.choice3_text.errors }}
                    <label class="choice_label" for="{{ form.choice3_text.id_for_label }}">Choice 3: </label>
                    {{ form.choice3_text }}
                </div>

                <div class="choice_correct_wrapper">
                    {{ form.choice3_correctness.errors }}
                    <label class="choice3_correct_label" for="{{ form.choice3_correctness.id_for_label }}"></label>
                    {{ form.choice3_correctness }}
                </div>

            </div>

            <div class="clear"></div>

            <div class="choice4">

                <div class="choice_text_wrapper">
                    {{ form.choice4_text.errors }}
                    <label class="choice_label" for="{{ form.choice4_text.id_for_label }}">Choice 4: </label>
                    {{ form.choice4_text }}
                </div>

                <div class="choice_correct_wrapper">
                    {{ form.choice4_correctness.errors }}
                    <label class="choice4_correct_label" for="{{ form.choice4_correctness.id_for_label }}"></label>
                    {{ form.choice4_correctness }}
                </div>

            </div>

            <div class="clear"></div>

            <input class="submit_button" type="submit" value={{ next_submit }}>
        </form>

    </div>





</body>

</body>

</html>

quiz/templates/quiz/create_quiz.html
<!DOCTYPE html>
<html lang="en">

<head>

    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'quiz/create_quiz.css' %}">

    <meta charset="UTF-8">
    <title>Create Quiz</title>

</head>

<body>
    
    {% include 'quiz/navbar.html' %}

    <div class="form_wrapper">

        <h1 class="form_name">Create Quiz</h1>
        <form action="" method="post">
            {% csrf_token %}
            <div class="error_text">
                {{ form.non_field_errors }}
            </div>

            <div class="quiz_name_wrapper">
                {{ form.quiz_name.errors }}
                <label class="quiz_name_label" for="{{ form.quiz_name.id_for_label }}">Quiz Name: </label>
                {{ form.quiz_name }}
            </div>

            <div class="num_questions_wrapper">
                <div class="error_text">
                    {{ form.num_questions.errors }}
                </div>

                <label class="num_questions_label" for="{{ form.num_questions.id_for_label }}">Number of Questions:
                </label>
                {{ form.num_questions }}
            </div>

            <input class="submit_button" type="submit" value="Next">
        </form>

    </div>
</body>

</html>

quiz/templates/quiz/expired.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Skill Ninja</title>
</head>
<body>
    <p>Code expired</p>
</body>
</html>

quiz/templates/quiz/index.html
<!DOCTYPE html>

<html lang="en">

<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'quiz/index.css' %}">
    <meta charset="UTF-8">
    <title>Index</title>

</head>

<body>
   
{% include 'quiz/navbar.html' %}
       <div class="secondpart">
        <div class="entercode_container">
            <form id="code_form" autocomplete="off" action="{% url 'quiz:exam' %}" method="post">
                {% csrf_token %}
                <p>Enter the Name</p>
            <input type="text" value="" name="name"></input>
                <p>Enter the code</p>
            <input type="text" value="" name="code"></input>
            <div class="button">
                <button class="button-17" type="submit" form="code_form" value="Submit">Join</button>

                <!-- <input class="button-17" type="submit" value="Join"> -->
            </div>
    
            </form>
            
           
        
           </div>
       </div>
</body>

</html>

quiz/templates/quiz/navbar.html
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'quiz/navbar.css' %}">


</head>
<section class="topnav">
    <a href="">Bolgatty</a>
    <a href="/">Home</a>
    <a href="{% url 'quiz:report' %}">Report</a>
    <a href="{% url 'quiz:allquiz' %}">quiz</a>
    <a href="">admin</a>
    <a href="">exam</a>
    
</section>

quiz/templates/quiz/report.html
{% load static %}
{% include 'quiz/navbar.html' %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'quiz/report.css' %}">

</head>
<table id="results">
    <tr>
        <td>
            Name
        </td>
        <td>
            Quiz Name
        </td>
        <td>
            Correct Answer

        </td>

        <td>
            Total questions
        </td>
    </tr>
    {% if candidates %}
        {% for person in candidates %}
        <tr>
            <td>
                {{ person.name }}
            </td>
            <td>{{ person.quiz_name }}</td>
            <td>{{ person.correct_qn }}</td>
            <td>{{ person.total_qn }}</td>
           
        </tr>
       

        {% endfor %}
{% else %}
    <p>No quizzes are available.</p>
{% endif %}
</table>

quiz/templates/quiz/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'quiz/results.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'quiz/navbar.css' %}">

    <meta charset="UTF-8">
    <title>Results</title>
</head>

<body>
    <section class="topnav">
        <a href="/">Home</a>
       
    </section>

    <div class="result_container">

        <h1 class="results_title">Results</h1>
        <p class="correct_to_total"> Total marks :  {{ num_correct }}/{{ total_questions }}</p>

        {% if accuracy_over_75 %}
            <p class="accuracy_good">{{ accuracy_formatted }}</p>
            <p>Congragulations</p>



        {% else %}
            <p class="accuracy_bad">{{ accuracy_formatted }}</p>
            <p>Better Luck Next Time :)</p>
        {% endif %}
    
    </div>
   
</body>
</html>

quiz/templates/quiz/single_question.html
<!DOCTYPE html>
<html id="html_delete" lang="en">

<head>
  {% load static %}

  <link rel="stylesheet" type="text/css" href="{% static 'quiz/single_question.css' %}">

  <meta charset="UTF-8">
  <title>Skill Ninja</title>
</head>

<body>
  <form id="hidden_form" action="{% url 'quiz:vote' quiz.id current_question.question_num name %}" method="post">
    {% csrf_token %}
      {% for choice in current_question.choice_set.all %}
      <input type="radio" name="choice" id="input{{ choice.id }}" value="{{ choice.id }}">
      <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
      {% endfor %}
  
  </form>


  <div class="top">
    <div class="timer">
      <div class="container">
        <img src="{% static 'quiz/images/circle.png' %}" alt="Snow">

        <div class="centered">5</div>
      </div>
    </div>
    <img id="post" src="{% static 'quiz/images/next.png' %}" alt="" class="next">
    <!-- <button class="next">Next</button> -->
  </div>
  <div class="bottom">
    <div class="question">
      <p>{{ current_question.question_text }}</p>
      {% if error_message %}
      <p><strong>{{ error_message }}</strong></p>
      {% endif %}
      <img src="{% static 'quiz/images/code.jpg' %}" alt="" width="300px" height="200px">
    </div>

    <div class="options">
      <ul id="q_options">
        {% for choice in current_question.choice_set.all %}
        <li id="{{ choice.id }}">
          {{ choice.choice_text }}
        </li>
        {% endfor %}
      </ul>

    </div>

</body>
<script defer>

  // const mydata = JSON.parse(document.getElementById('gem').textContent);
  document.getElementById("hidden_form").style.display="none";
  // document.getElementById("csrf").value 
  var csrftoken = '{{ csrf_token }}'
var selected_choice=""
  const ul = document.getElementById('q_options');
  const listItems = ul.getElementsByTagName('li');
  // Loop through the NodeList object.
  for (let i = 0; i <= listItems.length - 1; i++) {
    // console.log (listItems[i]);
    listItems[i].addEventListener('click', () => {
      console.log("clicked " + i);
      console.log('{{ gem }}');
      console.log(listItems[i].id);
      selected_choice=listItems[i].id;
      document.getElementById(listItems[i].id).style.backgroundColor = "#f0a82b";

      for (let j = 0; j <= listItems.length - 1; j++) {
        if(i!=j){
          document.getElementById(listItems[j].id).style.backgroundColor = "aqua";

        }
      }
      document.getElementById("input"+listItems[i].id).checked = true;




    })
  }
  document.getElementById('post').onclick = () => {
    console.log(document.getElementById(selected_choice).innerText,'{{ gem }}');
    if (document.getElementById(selected_choice).innerText =='{{ gem }}')
    {
      document.getElementById(selected_choice).style.backgroundColor = "green";
    }
    else
    {
      document.getElementById(selected_choice).style.backgroundColor = "red";

    }
    setTimeout(()=> {
      document.getElementById("hidden_form").submit();
      }
      ,3000);
    

  }

</script>

</html>

quiz/templates/quiz/single_quiz.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'quiz/single_quiz.css' %}">

    <meta charset="UTF-8">
    <title>Single Quiz</title>
</head>

<body>


    <div class="full_container">
       
        <h1 class="quiz_title">{{ quiz.quiz_title }}</h1>
   
        <h4 class="num_questions">{{ num_questions }} Questions</h4>
        <div class="home_button">
            <a  href="{% url 'quiz:candidate_update' quizid 1 token %}">Start Quiz</a>

            
        </div>


    </div>

</body>

</html>